### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by zilveer** [rhelmot/nclib#3]
Hello,
I am running the tutorial found at: [https://nclib.readthedocs.io/en/latest/netcat.html](https://nclib.readthedocs.io/en/latest/netcat.html) and have issues to run it.
Can you please tell me what the issue could be?

This is the commands I run as well as the error message shown.

```
>>> import nclib
>>> nc = nclib.Netcat(('127.0.0.1', 50001), udp=True, verbose=True)
>>> nc.send('\x00\x0dHello, world!')
======== Sending (15) ========
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 504, in se
nd
    self._log_send(s)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 230, in _l
og_send
    self._log_something(data, self.echo_send_prefix)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 213, in _l
og_something
    self._print_lines(data, prefix)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 237, in _p
rint_lines
    print(prefix + line)
TypeError: can't concat str to bytes
```

Thanks for your reply.

**Comment by rhelmot** [comment]
Hi! If you are using python 3, you have to send bytes objects instead of strings. So you should say `nc.send(b'\x00\x0dHello, world!')`. I will update the example accordingly.

**Comment by zilveer** [comment]
Hi,
in python2.7 I get this error message:
```
zilveer@9eb9:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nclib
>>> nc = nclib.Netcat(('127.0.0.1', 50001), udp=True, verbose=True)
>>> nc.send('\x00\x0dHello, world!')
======== Sending (15) ========
Hello, world!
>>> nc.recv()
======== Receiving 4096B or until timeout (default) ========
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nclib/netcat.py", line 335, in re
cv
    raise NetcatError('Socket error!')
nclib.errors.NetcatError: Socket error!
```

and in python3 (3.6.2) I get this error:
```
zilveer@9eb9:~$ python3
Python 3.6.2 (default, Jul 20 2017, 08:43:29)
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nclib
>>> nc = nclib.Netcat(('127.0.0.1', 50001), udp=True, verbose=True)
>>> nc.send(b'\x00\x0dHello, world!')
======== Sending (15) ========
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 504, in se
nd
    self._log_send(s)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 230, in _l
og_send
    self._log_something(data, self.echo_send_prefix)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 213, in _l
og_something
    self._print_lines(data, prefix)
  File "/usr/local/lib/python3.6/dist-packages/nclib/netcat.py", line 236, in _p
rint_lines
    for line in s.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

So I still get the errors :/

**Comment by rhelmot** [comment]
I was unable to reproduce your py2 bug, but I have fixed the string literals to be bytestring literals so that py3 will work. I'm not sure what to tell you about your py2 issue! It looks like something weird going on with your operating system and its ability to let you use a UDP socket.

**Comment by zilveer** [comment]
@rhelmot I use Ubuntu 16.04, maybe Ubuntu doesnt have full support for python, I dont know? Is Debian better?

When I set `udp=False` I get the same issue.

What I want to achieve with nclib, correct me if I am wrong, is to: 

1. is to initiate a netcat connection, in my case to TCP
2. Send a command through TCP instance
3. Get the result

Isnt nclib for that purpose?

**Comment by rhelmot** [comment]
Yeah absolutely, that's 100% the use case. I'm using ubuntu 16.10 right now and it's definitely working for me.

![image](https://user-images.githubusercontent.com/2498805/29994778-b2572e04-8f8c-11e7-8a59-62d2c814ef33.png)

The only thing I can think of is for you to look at what `strace` has to say about what's happening under the covers in python.

**Comment by zilveer** [comment]
Ok thanks for confirm to my questions.
But I still get the same issue, both on Ubuntu 16.04, Centos 7 and Windows 7.

Really strange error:
```
======== Receiving 4096B or until timeout (default) ========
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nclib/netcat.py", line 335, in re
cv
    raise NetcatError('Socket error!')
nclib.errors.NetcatError: Socket error!
```
Could it be something wrong on the Socket library ?
